version: "3.8"
services:
  mariadb:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: welcome
    ports:
      - 3306:3306
  lifehackd:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./data:/home/lifehackd/data
    secrets:
      - lifehackd-config

secrets:
  lifehackd-config:
    file: ./config.json
